name: Build, Pack & Publish

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
      - name: Test and Pack
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet tool install Cake.Tool --version 1.1.0
          dotnet tool restore
          dotnet cake --target=Pack --verbosity=verbose
      - name: Publish Solana.Unity.Anchor
        uses: Rebel028/publish-nuget@v2.8.0
        with:
          PROJECT_FILE_PATH: Solana.Unity.Anchor/Solana.Unity.Anchor.csproj
          PACKAGE_NAME: Solana.Unity.Anchor
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          INCLUDE_SYMBOLS: true
      - name: Publish Solana.Unity.Anchor.Tool
        uses: Rebel028/publish-nuget@v2.8.0
        with:
          PROJECT_FILE_PATH: Solana.Unity.Anchor.Tool/Solana.Unity.Anchor.Tool.csproj
          PACKAGE_NAME: Solana.Unity.Anchor.Tool
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          INCLUDE_SYMBOLS: true
      - name: Publish Solana.Unity.Anchor.SourceGenerator
        uses: Rebel028/publish-nuget@v2.8.0
        with:
          PROJECT_FILE_PATH: Solana.Unity.Anchor.SourceGenerator/Solana.Unity.Anchor.SourceGenerator.csproj
          PACKAGE_NAME: Solana.Unity.Anchor.SourceGenerator
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          INCLUDE_SYMBOLS: true